language: php

php:
    - 7.2
    - 7.3

cache:
    directories:
        - ~/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - composer update

script:
    - composer validate --strict

    - composer analyse

    - composer test
